# Generated by Django 2.2.2 on 2019-06-11 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0007_auto_20190611_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockrecord',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partner.Currency'),
        ),
    ]
