# Generated by Django 2.2.2 on 2019-06-13 11:43

from django.db import migrations, models
import oscar.core.utils


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0010_auto_20190612_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerate',
            name='base_currency',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='currency',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='stockrecord',
            name='price_currency',
            field=models.CharField(default=oscar.core.utils.get_default_currency, max_length=12, verbose_name='Currency'),
        ),
    ]
