# Generated by Django 2.2.2 on 2019-06-13 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0011_auto_20190613_1143'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Currency',
        ),
    ]
