# Generated by Django 2.2.2 on 2019-06-11 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0008_stockrecord_currency'),
        ('basket', '0008_auto_20181115_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='baskets', to='partner.Currency'),
        ),
    ]
