# Generated by Django 2.2.2 on 2019-06-11 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0009_basket_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baskets', to='partner.Currency'),
        ),
    ]
