# Generated by Django 2.2.2 on 2019-06-12 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0010_auto_20190611_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='baskets', to='partner.Currency'),
        ),
    ]
