# Generated by Django 2.2.2 on 2019-06-13 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0011_auto_20190612_0956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='line',
            name='price_currency',
        ),
    ]
