# Generated by Django 2.2.2 on 2019-06-13 08:47

from django.db import migrations, models
import django.db.models.deletion
import oscar.core.utils


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0010_auto_20190612_1207'),
        ('basket', '0012_remove_line_price_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='basket_lines', to='partner.Currency'),
        ),
        migrations.AddField(
            model_name='line',
            name='price_currency',
            field=models.CharField(default=oscar.core.utils.get_default_currency, max_length=12, verbose_name='Currency'),
        ),
    ]
