# Generated by Django 2.2.2 on 2019-06-13 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0013_auto_20190613_0847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='line',
            name='currency',
        ),
        migrations.AlterField(
            model_name='line',
            name='price_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='basket_lines', to='partner.Currency'),
        ),
    ]
