# Generated by Django 2.2.2 on 2019-06-13 11:43

from django.db import migrations, models
import oscar.core.utils


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0014_auto_20190613_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='currency',
            field=models.CharField(default=oscar.core.utils.get_default_currency, max_length=3),
        ),
        migrations.AlterField(
            model_name='line',
            name='price_currency',
            field=models.CharField(default=oscar.core.utils.get_default_currency, max_length=12, verbose_name='Currency'),
        ),
    ]
