# Generated by Django 2.2.2 on 2019-06-13 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0015_auto_20190613_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='currency',
        ),
    ]
