# Generated by Django 2.2.2 on 2019-06-13 13:39

from django.db import migrations, models
import oscar.core.utils


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0016_remove_basket_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='currency',
            field=models.CharField(default=oscar.core.utils.get_default_currency, max_length=3),
        ),
    ]
