# Generated by Django 2.2.2 on 2019-06-13 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0017_basket_currency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket',
            old_name='currency',
            new_name='_currency',
        ),
    ]
