# Generated by Django 2.2.2 on 2019-06-14 06:59

from django.db import migrations, models
import oscar.core.utils


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0008_auto_20181115_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='benefit',
            name='currency',
            field=models.CharField(default=oscar.core.utils.get_default_currency, max_length=3),
        ),
    ]
