# Generated by Django 2.2.2 on 2019-06-14 10:30

from django.db import migrations, models
import oscar.core.utils


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0009_benefit_currency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='benefit',
            options={},
        ),
        migrations.AlterModelOptions(
            name='condition',
            options={},
        ),
        migrations.AddField(
            model_name='condition',
            name='currency',
            field=models.CharField(default=oscar.core.utils.get_default_currency, max_length=3),
        ),
    ]
