# Generated by Django 2.2.2 on 2019-06-17 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0010_auto_20190614_1030'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyAwareValueCondition',
            fields=[
            ],
            options={
                'abstract': False,
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('offer.valuecondition',),
        ),
    ]
